# Generated by Django 3.0.8 on 2020-07-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatName', models.TextField()),
                ('chatTime', models.DateTimeField(auto_now_add=True)),
                ('chatContent', models.TextField(blank=True)),
                ('lessonId', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonId', models.TextField(unique=True)),
                ('lessonName', models.TextField()),
                ('lessonNotice', models.TextField(blank=True)),
                ('codeContent', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.TextField()),
                ('studentId', models.TextField(unique=True)),
                ('studentEmail', models.TextField(unique=True)),
                ('studentPassword', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentEmail', models.TextField()),
                ('studentName', models.TextField()),
                ('studentId', models.TextField()),
                ('lessonId', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.TextField()),
                ('teacherId', models.TextField(unique=True)),
                ('teacherEmail', models.TextField(unique=True)),
                ('teacherPassword', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherEmail', models.TextField()),
                ('teacherName', models.TextField()),
                ('teacherId', models.TextField()),
                ('lessonId', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminName', models.TextField(unique=True)),
                ('adminPassword', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WaitLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonId', models.TextField()),
                ('studentId', models.TextField()),
                ('studentName', models.TextField()),
            ],
        ),
    ]
