# Generated by Django 3.0.8 on 2020-07-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
