# Generated by Django 3.0.8 on 2020-07-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_delete_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonId', models.TextField(unique=True)),
                ('lessonName', models.TextField()),
                ('lessonNotice', models.TextField(blank=True)),
                ('codeContent', models.TextField(blank=True)),
            ],
        ),
    ]
